# Generated by Django 4.0.2 on 2022-05-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='discord',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teammember',
            name='twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('wiki', 'Wiki'), ('youtube', 'Youtube'), ('twitter', 'Twitter'), ('artykuł', 'Artykuł'), ('cooperation', 'Cooperation')], default='artykuł', max_length=50),
        ),
    ]
